#! /bin/bash

sudo killall openvpn
sudo rm -f /etc/resolv.conf
#sudo cp /etc/resolv.conf.orig /etc/resolv.conf
sudo ln -s /run/resolvconf/resolv.conf /etc/resolv.conf
sleep 2
echo "$(cat /etc/resolv.conf)"
echo " "
sleep 5
ps aux | grep openvpn
sudo ip route add default via 192.168.15.1 dev enp3s0 onlink
