#! /bin/bash

case $1 in
	"aws"|"surfshark-saopaulo"|"surfshark-florida")

	;;
	*)
		echo "Usage (aws|surfshark-saopaulo|surfshark-florida)"
		exit 0
	;;
esac

sudo openvpn --config /etc/openvpn/$1.ovpn --daemon
sleep 2

if ip address | grep -q "tun0"
then
  echo "Connected to $1 VPN"
  sleep 1
  sudo ~/bin/resolvGenerator
  echo "$(cat /etc/resolv.conf | grep 'nameserver')"
  #sudo ufw enable
  ip route | grep default > ~/.temp/iproutevalue
  sudo ip route del $(cat ~/.temp/iproutevalue)
  echo "Running DNS leak test"
  sleep 5
  dnstest
else
  echo "Connection failed"
  sudo killall openvpn
fi
