#! /bin/bash

sudo openvpn --config /etc/openvpn/vpn2.ovpn --daemon
sleep 2

if ip address | grep -q "tun0"
then
  echo "Connected to SURFSHARK VPN"
  sudo ~/bin/resolvGenerator
  echo "$(cat /etc/resolv.conf | grep 'nameserver')"
  sudo ufw enable
  ip route | grep default > ~/.temp/iproutevalue
  sudo ip route del $(cat ~/.temp/iproutevalue)
  echo "Running DNS leak test"
  sleep 5
  dnstest
else
  echo "Connection failed"
  sudo killall openvpn
fi
